# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-03 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_storage_workers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
