# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_delete_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idmenu', models.AutoField(primary_key=True, serialize=False)),
                ('menuname', models.CharField(max_length=50)),
                ('firstitemvalue', models.IntegerField()),
                ('seconditemvalue', models.IntegerField()),
                ('thirditemvalue', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cooktime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idorder', models.AutoField(primary_key=True, serialize=False)),
                ('orderdatetime', models.DateTimeField()),
                ('ordername', models.CharField(max_length=50)),
                ('orderphone', models.IntegerField()),
                ('orderprice', models.IntegerField()),
                ('ordercomplete', models.CharField(max_length=50)),
                ('orderfirstdish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_firstrelated', to='Tables.Menu')),
                ('orderseconddish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_secondrelated', to='Tables.Menu')),
                ('orderthirddish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_thirdrelated', to='Tables.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('idstorage', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=50)),
                ('itemdate', models.DateField()),
                ('itemvalue', models.IntegerField(default=100)),
                ('itemtouse', models.DateField()),
                ('itemcost', models.IntegerField(default=100)),
                ('itemprovider', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='idfirstitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_menu_firstitemrelated', to='Tables.Storage'),
        ),
        migrations.AddField(
            model_name='menu',
            name='idsecondtitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_menu_seconditemrelated', to='Tables.Storage'),
        ),
        migrations.AddField(
            model_name='menu',
            name='idthirdtitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_menu_thirditemrelated', to='Tables.Storage'),
        ),
    ]
