# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0005_auto_20170107_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cooktime',
            field=models.TimeField(),
        ),
    ]
