# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0006_auto_20170107_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderseconddish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_secondrelated', to='Tables.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderthirddish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_thirdrelated', to='Tables.Menu'),
        ),
    ]
