# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0008_auto_20170107_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobname',
            field=models.CharField(max_length=20, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobrules',
            field=models.CharField(max_length=45, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobsalary',
            field=models.IntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobtodo',
            field=models.CharField(max_length=45, verbose_name='What to do'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cooktime',
            field=models.TimeField(verbose_name='Cook time'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='firstitemvalue',
            field=models.IntegerField(verbose_name='Value of the first'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='idfirstitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_menu_firstitemrelated', to='Tables.Storage', verbose_name='First product'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='idsecondtitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_menu_seconditemrelated', to='Tables.Storage', verbose_name='Second product'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='idthirdtitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_menu_thirditemrelated', to='Tables.Storage', verbose_name='Third product'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuname',
            field=models.CharField(max_length=50, verbose_name='Dish'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='seconditemvalue',
            field=models.IntegerField(verbose_name='Value of the second'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thirditemvalue',
            field=models.IntegerField(verbose_name='Value of the third'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordercomplete',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdatetime',
            field=models.DateTimeField(verbose_name='Order date and time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderfirstdish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_firstrelated', to='Tables.Menu', verbose_name='First dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordername',
            field=models.CharField(max_length=50, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderphone',
            field=models.IntegerField(verbose_name="Customer's phone"),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderprice',
            field=models.IntegerField(verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderseconddish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_secondrelated', to='Tables.Menu', verbose_name='Second dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderthirddish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables_order_thirdrelated', to='Tables.Menu', verbose_name='Third dish'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='itemcost',
            field=models.IntegerField(default=100, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='itemdate',
            field=models.DateField(verbose_name='Date of production'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='itemname',
            field=models.CharField(max_length=50, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='itemprovider',
            field=models.CharField(max_length=50, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='itemtouse',
            field=models.DateField(verbose_name='Date to use'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='itemvalue',
            field=models.IntegerField(default=100, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workeraddress',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workerage',
            field=models.IntegerField(default=20, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workergender',
            field=models.CharField(max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workername',
            field=models.CharField(max_length=50, verbose_name='Worker'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workerpass',
            field=models.CharField(max_length=70, verbose_name='Passport'),
        ),
    ]
