# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0009_auto_20170107_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderworker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Tables.Workers', verbose_name='Order waiter'),
            preserve_default=False,
        ),
    ]
