# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0010_order_orderworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.Workers', verbose_name='Order waiter'),
        ),
    ]
