# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0011_auto_20170108_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='workerjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.Jobs', verbose_name='Job'),
        ),
    ]
